### ISSUE TITLE
Error obtaining questions running on physical device

### ISSUE THREAD

**Issue by AbanoubG** [lohanidamodar/flutter_opentrivia#1]
When I run the application on an emulator, the questions appear. However, when I package the application using flutter build apk and then run the apk on my physical device (Pixel 3) every time I launch a category and attempt to begin a quiz, I receive the "Cannot reach the servers. Check your internet connection" even though my internet connection is good.

**Comment by lohanidamodar** [comment]
try running on debug mode in your physical device and check the error and post the log.

**Comment by AbanoubG** [comment]
Figured it out..
Add ` <uses-permission android:name="android.permission.INTERNET" /> `
to AndroidManifest.xml to ensure release apk works
